CREATE TABLE SORA.RADIOHEAD (
SONG_NAME VARCHAR(80),
ALBUM VARCHAR(80),
ARTIST VARCHAR(80),
RELEASE_DATE VARCHAR(80),
SONG_LENGTH INTEGER,
POPULARITY DOUBLE,
DANCEABILITY DOUBLE,
ACOUSTICNESS DOUBLE,
ENERGY DOUBLE,
INSTRUMENTALNESS DOUBLE,
LIVENESS DOUBLE,
LOUDNESS DOUBLE,
SPEECHINESS DOUBLE,
TEMPO DOUBLE,
TIME_SIGNATURE DOUBLE,
primary key (song_name, album)

);

select * from SORA.RADIOHEAD;
select count(*) from sora.soratable;